### ISSUE TITLE
Task 1 : Console Application

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS63#1]
Topic Covered:
Installation Nodejs

Install Node js in your system and run the command

`console.log("Hello ! world");`

Share me the screenshots of the output that you will get just like the example below on the comments

![Image](https://user-images.githubusercontent.com/128008784/238532387-38b79483-f666-4a04-81f9-353cd0e9bc17.png)

**Comment by Oshinacharya1** [comment]
![Screenshot 2024-10-14 124034](https://github.com/user-attachments/assets/837b10e7-d40f-4565-9fc4-1c9d725559c4)

**Comment by komalallaparthi** [comment]
![Screenshot (384)](https://github.com/user-attachments/assets/e1ab13d5-7871-4f8a-9189-14f499c5bb6b)

**Comment by Nikhil5918** [comment]
[
![Screenshot (4)](https://github.com/user-attachments/assets/96039080-29c8-4292-92f5-434b47c17515)
](url)
