### ISSUE TITLE
Assignment 1 : Portfolio

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS63#16]
**Task: Simple Personal Portfolio**

**Objective:** Build a personal portfolio website with four main pages—Home, Contact, Projects, and About—using React and React Router for seamless navigation.

**Requirements:**

1. **Basic Page Layout (Home, About, Projects, Contact):**
   - **Home Page:** Brief introduction and welcome message, with links to other pages.
   - **About Page:** Information about yourself, such as background, skills, interests, and a profile picture.
   - **Projects Page:** Display a list of your projects with details like title, description, tech stack, and links to project demos or GitHub repositories.
   - **Contact Page:** Simple contact form with fields for name, email, and message. You don’t need to handle form submissions, but consider a “Thank you” message or pop-up for when the form is submitted.

2. **Navigation (React Router):**
   - Set up React Router to enable navigation between pages without reloading the page.
   - Use a **navigation bar** at the top with links to Home, About, Projects, and Contact.
   - Ensure that the active link is highlighted for better user experience.

3. **React Component Structure:**
   - Use separate React components for each page to keep the code modular and organized.
   - Each page should have its own folder with a React component file and a CSS file (optional for styling).

4. **Styling:**
   - Style the portfolio using CSS to give it a cohesive look.
   - Create a responsive design so it looks good on both desktop and mobile devices.

5. **Bonus (Optional):**
   - Add animations to transitions between pages.
   - Use a CSS framework like Bootstrap or Tailwind for a polished design.

**Comment by Oshinacharya1** [comment]
https://github.com/Oshinacharya1/Portfolio/tree/master
