### ISSUE TITLE
Task 2: Running Javascript File

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS63#2]
Here’s a task for running a JavaScript file through Node.js:

#### Objective:
Learn how to run a JavaScript file using Node.js from the terminal/command line.

#### Prerequisites:
- Node.js must be installed on your machine. If not, download and install it from [here](https://nodejs.org/).
- A JavaScript file ready to run (e.g., `app.js`).

#### Steps:

1. **Verify Node.js Installation:**
   - Open a terminal (or command prompt on Windows).
   - Run the following command to ensure Node.js is installed:
     ```bash
     node -v
     ```
   - This should output the Node.js version installed on your system.

2. **Create a JavaScript File:**
   - Open your code editor and create a new file (e.g., `app.js`).
   - Add the following example code:
     ```javascript
     console.log("Hello, Node.js is running!");
     ```

3. **Navigate to the File's Directory:**
   - In the terminal, navigate to the directory where your `app.js` file is located using the `cd` command:
     ```bash
     cd path/to/your/file
     ```

4. **Run the JavaScript File:**
   - Execute the JavaScript file using Node.js by typing the following command:
     ```bash
     node app.js
     ```
   - You should see the output:
     ```
     Hello, Node.js is running!
     ```

#### Deliverables:
- A screenshot of the terminal showing the output of running the `app.js` file.

**Comment by Oshinacharya1** [comment]
![js](https://github.com/user-attachments/assets/87edc72d-3b49-4908-8c5a-d824e2e68f27)

**Comment by Nikhil5918** [comment]
![Screenshot (6)](https://github.com/user-attachments/assets/c09082e8-fc63-476c-8fd6-8128696a4a81)

**Comment by komalallaparthi** [comment]
![Screenshot (386)](https://github.com/user-attachments/assets/e15a3540-4c9b-441a-8cf6-cb71c24aa925)
