### ISSUE TITLE
Task 3 : GIthub Repositary

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS63#3]
# Task 3: Creating a Repository and Pushing Files
## Objective:
Create a new repository on GitHub and push files to it using Git.

## Task Overview

- Learn how to create a repository on GitHub.
- Initialize a local Git repository and connect it to the remote repository.
- Push files from your local machine to the remote repository.

## Task Details

1. Watch a tutorial video or read an article on creating repositories on GitHub.
2. Sign in to your GitHub account.
3. Click on the "+" icon in the top-right corner and select "New repository" from the dropdown menu.
4. Provide a name for your repository (e.g., "frontend-bootcamp-tasks") and an optional description.
5. Choose the visibility (public or private) for your repository.
6. Optionally, select the option to initialize the repository with a README file.
7. Click on the "Create repository" button to create the repository on GitHub.

Now, let's move to the local machine:

Open a terminal or command prompt and navigate to your project directory.
Initialize a new Git repository in your project directory using the command:

`git init`

Add the files you want to push to the repository. For example, if you have an HTML file called "index.html" and a CSS file called "styles.css" in your project directory,

Style and create anything you wish for which contains at least 10 element tags like div , h1 , p , a , all the other try to style each and every one of them in different variants

 use the following command to add them:

`git add .`

Commit the changes with a descriptive message using the command:

`git commit -m "Initial commit"`
Connect your local repository to the remote repository on GitHub using the following command:

`git remote add origin https://github.com/your-username/frontend-bootcamp-tasks.git`

Push the changes to the remote repository using the command:
`git push origin master`

**Verify that the files have been pushed to your GitHub repository by visiting the repository's page on GitHub.**

## Task Submission

Take a screenshot of your GitHub repository showing the pushed files.
Share the screenshot on the issues comment of this issue.

**Comment by Oshinacharya1** [comment]
![Screenshot 2024-10-14 141907](https://github.com/user-attachments/assets/5539730f-d7fb-4481-9f45-4677659f876f)
![Screenshot 2024-10-14 141810](https://github.com/user-attachments/assets/5026b5b1-9b6f-49ad-825a-d83537a10a58)

**Comment by komalallaparthi** [comment]
![Screenshot (387)](https://github.com/user-attachments/assets/e9ae0cea-50fd-4c44-bb6a-d83edc5b78f0)

**Comment by Nikhil5918** [comment]
![Screenshot (7)](https://github.com/user-attachments/assets/6bab5bef-f030-41d5-a799-5984797bb8fc)

**Comment by komalallaparthi** [comment]
![Screenshot (388)](https://github.com/user-attachments/assets/328f8cfc-7a43-4649-aef2-506853c41aae)
