### ISSUE TITLE
Task 4 : HTML Semantics

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS63#5]
# **Task 4: HTML Semantics **
## **Objective:**
 Apply HTML semantics in real world

## Task Overview

- Understand the importance of HTML semantics in web development.
- Apply CSS styling to the HTML component using inline styles. (optional)

## Task Details

Read an article about the importance of HTML semantics in web development.
[HTML Semantics Link ](https://developer.mozilla.org/en-US/docs/Glossary/Semantics)

### Implement HTML semantics: 

1. Inside the index.html, use HTML semantics to structure the content.
2. Add semantic HTML tags such as` <header>, <nav>, <main>, <section>, <article>, <aside>, and <footer>` to represent different sections of the component's content.
3. Place some placeholder content within each semantic tag (e.g., headings, paragraphs, and lists).
4. Apply CSS styling with inline styles: (optional)

This will be useful in the future to use inline styles in React JSX to apply CSS styling to the semantic components.
.
Optional : Experiment with different CSS properties such as background-color, color, font-size, padding, margin, and border.

### Render the Semantic components:

1. Import and render the Semantic component in another component
2. Verify that the Semantic components are rendered correctly and the CSS styles are applied through the inspect panel.(optional)

### Test and refine the styling:

- Open your project in a web browser and inspect the rendered semantic components.
- Adjust the CSS styles and properties as needed to achieve the desired visual appearance. (optional)
- Refresh the browser to see the updated styles.

## Task Submission
Take a screenshot of the rendered semantic components in the browser.
Share the screenshot of the output and the code that you have written in the issue comment box.
Don't forget to mention GitHub URL and your name in the comment section.

**Comment by Oshinacharya1** [comment]
![html](https://github.com/user-attachments/assets/6b10fd56-f755-42dd-8a83-65623932dc17)
![css](https://github.com/user-attachments/assets/cf20884e-b2d8-4765-87b3-c1709468e982)
![output](https://github.com/user-attachments/assets/fc77dce4-0703-4a47-95c9-8c1598ad61e8)

**Comment by Nikhil5918** [comment]
![Screenshot (8)](https://github.com/user-attachments/assets/23a14a5a-b1d3-4edf-8e39-ebb97c619f52)
![Screenshot (9)](https://github.com/user-attachments/assets/0b5a7013-8073-4bdc-a4a2-2f766694643a)
![Screenshot (10)](https://github.com/user-attachments/assets/11833563-3c84-4e06-accd-223cf5c7f6a0)

**Comment by komalallaparthi** [comment]
![Screenshot (391)](https://github.com/user-attachments/assets/0074b4e4-8b66-46db-a36a-e0f607cc690a)
![Screenshot (390)](https://github.com/user-attachments/assets/b4271c45-d9ca-4063-8d1b-0015a933b75c)
![Screenshot (389)](https://github.com/user-attachments/assets/a2951672-b9bf-46a9-8f2d-ec17ec7fc810)

**Comment by komalallaparthi** [comment]
![Screenshot (392)](https://github.com/user-attachments/assets/f9dbfcc8-2ef1-4e59-b90d-9d0a4df2f7a9)
![Screenshot (393)](https://github.com/user-attachments/assets/2e5840f0-d78b-46c8-b72b-b04c5810859a)
![Screenshot (394)](https://github.com/user-attachments/assets/3192a61b-d82e-42c0-a154-b0e40fc83d9f)

**Comment by Nikhil5918** [comment]
![Screenshot (13)](https://github.com/user-attachments/assets/2ae0103e-eb41-4135-bf6a-def5683b4d4b)
![Screenshot (14)](https://github.com/user-attachments/assets/7a1437a8-4a8d-4344-b8f4-42dc265e17a4)
![Screenshot (15)](https://github.com/user-attachments/assets/37b2e268-6430-4279-bf3f-270c470be070)
![Screenshot (16)](https://github.com/user-attachments/assets/57ee728d-67be-4884-9c7f-af720d907c10)

**Comment by Nikhil5918** [comment]
![Screenshot (17)](https://github.com/user-attachments/assets/85207a59-7eb0-4315-b972-d848b36e96f3)
![Screenshot (18)](https://github.com/user-attachments/assets/88ea1d20-e2ce-4600-9a40-47f444704492)
![Screenshot (19)](https://github.com/user-attachments/assets/8e4cd7f5-14c4-434a-8f6a-a5ec8cd3a04e)
