### ISSUE TITLE
Task 6 : React and CSS

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS63#7]
### Objective:
Apply CSS styling in a React project created with Vite.

### Task Overview
- Understand CSS styling and JavaScript variables.
- Apply CSS styles to React components using class names and inline styles.
- Use JavaScript variables to enhance interactivity in a React project.

#### 1. Review CSS Styling and JavaScript Variables
- Watch tutorials or read articles on CSS styling and JavaScript variables.
  - [Variables in JavaScript](https://www.youtube.com/watch?v=XgSjoHgy3Rk&ab_channel=ProgrammingwithMosh)
  - [CSS Styling Methodology](https://www.youtube.com/watch?v=WuvujA5facU&ab_channel=DanielWood)
- Familiarize yourself with CSS selectors, properties, values, and JavaScript variables.

#### 2. Set Up a React Project with Vite
- **Option 1:** Use `npx create-vite@latest project_name` to create a new React project.
- **Option 2:** Manually set up the project:
  ```bash
  mkdir react-styling
  cd react-styling
  npm init vite@latest
  ```

#### 3. Apply CSS Styling
1. Open the project in a code editor.
2. Choose a React component (e.g., `App.js`) to style.
3. Add CSS class names to HTML elements in the component.
4. Create a `styles.css` file in the `src` directory and write CSS styles for the class names.
5. Import the CSS file in the component file: `import './styles.css';`.
6. Make the design responsive and fluid.
7. Create at least 10 components (e.g., buttons, links, images, containers) and style them using CSS, showcasing various properties like padding, margin, border, color, background, height, width, and using units like `px`, `rem`, and `%`.

#### 4. Test and Refine
1. Start the development server: `npm run dev`.
2. Access the local server (e.g., `http://localhost:5173`) to check the styles.

### Task Submission
1. Take a screenshot of the rendered components in the browser.
2. Share the screenshot and the written code in the issue comment box.
3. Include the GitHub URL and your name in the comment section.

### Additional Note
Include the process of using Git for version control, including branching, committing, and merging, while completing the coding task.

**Comment by Oshinacharya1** [comment]
![Image](https://github.com/user-attachments/assets/70fee3c4-614b-462b-b8ba-ab8d438c8836)
![Image](https://github.com/user-attachments/assets/a7bbfde6-df23-46ec-8304-b6b5d89b6889)

**Comment by Oshinacharya1** [comment]
![Image](https://github.com/user-attachments/assets/7023561f-0340-44e3-b891-30704e46f099)
