### ISSUE TITLE
Task 8 : JS Basics

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS63#9]
### **JavaScript Basics Task: Build a Simple Data Dashboard**

---

### **Objective:**
Students will practice fundamental JavaScript concepts, including data types, functions, `Array.map`, and function calls, by building a simple data dashboard using React and Vite.

### **Task Overview:**
Students will create a React project that displays a list of users and their information using data from an array. They will use JavaScript functions to manipulate the data and render it dynamically on the page.

---

#### **1. Set Up the Project:**
- **Create a React project using Vite:**
  - Run `npm create vite@latest` to create a new React project.
  - Set up the project and install dependencies with `npm install`.
  - Start the development server using `npm run dev`.

#### **2. Data Types:**
- **Create an array of objects:**
  - Inside a `data.js` file, create an array of objects representing users. Each object should have properties like `name` (string), `age` (number), and `occupation` (string).
    ```js
    const users = [
      { name: "John", age: 30, occupation: "Engineer" },
      { name: "Jane", age: 25, occupation: "Designer" },
      { name: "Mike", age: 35, occupation: "Developer" }
    ];
    export default users;
    ```

#### **3. Functions:**
- **Create functions to display user details:**
  - Write a function that takes in the `users` array and returns a formatted string of each user’s name and occupation.
    ```js
    function formatUser(user) {
      return `${user.name} is a ${user.occupation}`;
    }
    ```

#### **4. `Array.map`:**
- **Use `.map()` to render the user list:**
  - In your React component, use the `Array.map()` function to loop through the `users` array and display each user's formatted details.
    ```js
    const UserList = () => {
      return (
        <div>
          {users.map((user) => (
            <p key={user.name}>{formatUser(user)}</p>
          ))}
        </div>
      );
    };
    ```

#### **5. Function Call:**
- **Call a function inside a React component:**
  - Ensure that `formatUser()` is called from within the React component to display the user information dynamically.

#### **6. Final Output:**
- **Render the UserList component:**
  - In your `App.js` file, render the `UserList` component, which will display the formatted user details.
  
    ```jsx
    import UserList from './UserList';
    
    function App() {
      return (
        <div>
          <h1>User Dashboard</h1>
          <UserList />
        </div>
      );
    }
    
    export default App;
    ```

---

### **Project Structure:**

- **App.jsx**: Main application file rendering the user dashboard.
- **UserList.jsx**: Component that renders the list of users.
- **data.jsx**: File containing the array of user objects.
- **functions.jsx** (optional): File for reusable functions like `formatUser`.

**Comment by komalallaparthi** [comment]
![Screenshot (396)](https://github.com/user-attachments/assets/fefd880d-4b80-4368-a461-52455fecefd6)

**Comment by GyurMay** [comment]
<img width="1011" alt="Screenshot 2024-10-24 at 1 54 08 PM" src="https://github.com/user-attachments/assets/f965eb74-106b-4b29-9793-a3a22e4fadba">

**Comment by Oshinacharya1** [comment]
![Screenshot 2024-10-24 131756](https://github.com/user-attachments/assets/a1b541d2-5de9-4184-9158-f9e5c4e33a62)

**Comment by GyurMay** [comment]
<img width="1005" alt="Screenshot 2024-10-24 at 2 28 00 PM" src="https://github.com/user-attachments/assets/bd8331b2-db1a-42bd-b2a4-32288faa6c0e">

![image](https://github.com/user-attachments/assets/9295a65b-54ec-4545-8b74-44bf11dc7a1d)
